[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
sep_inner = { open = "", close = "" }
separator = { fg = "reset", bg = "reset" }

[mgr]
border_symbol = " "
